global:
    scrape_interval:     15s
    evaluation_interval: 15s
  
    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: 'prometheus-stack-monitor'
  
  # Load and evaluate rules in this file every 'evaluation_interval' seconds.
  # rule_files:
    # - "first.rules"
    # - "second.rules"
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: redis-master-exporter
    static_configs:
    - targets: ['redis-master-exporter:9121']

  - job_name: redis-slave-1-exporter
    static_configs:
    - targets: ['redis-slave-1-exporter:9121']

  - job_name: redis-slave-2-exporter
    static_configs:
    - targets: ['redis-slave-2-exporter:9121']